Repository Solace-Health/solace-health-entry-widget, pull requests merged in 2024-03, with the labels that each got.

#12 [SOL-4153] Copy Updates
  dist/bundle.js
  package-lock.json
  src/Widget/index.tsx
Labels: enhancement

#13 Add DOB
  dist/bundle.js
  src/Widget/index.tsx
Labels: chore

#14 Styling for Webflow
  dist/bundle.js
  src/Widget/styles.ts
Labels: bug

#16 [SOL-4320] Add analytics.track when analytics present
  dist/bundle.js
  dist/index.html
  src/Widget/index.tsx
  src/types/index.ts
  src/utils/analytics.ts
Labels: enhancement
